apiVersion: apps/v1
kind: Deployment
metadata:
  name: cristiano-com-mais-raiva
  labels:
    app: teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste
  template:
    metadata:
      labels:
        app: teste
    spec:
      containers:
      - name: healthcheck
        image: dkcorreriadocker/flask:4.8
        env:
                - name: SQLALCHEMY_DATABASE_URI
                  value: "mysql+pymsql://ccosta:Email12@QW@34.204.189.20:3306"
                - name: REDISTOGO_URL
                  value: "redis://RBOJ9cCNoGCKhlEBwQLHri1g+atWgn4Xn4HwNUbtzoVxAYxkiYBi7aufl4MILv1nxBqR4L6NNzI0X6cE@34.204.189.20:6379"
        ports:
        - containerPort: 5000
